site_name: Mordant
repo_name: Mordant
repo_url: https://github.com/ajalt/mordant
site_description: "Mordant: Multiplatform text styling for Kotlin command-line applications"
site_author: AJ Alt
remote_branch: gh-pages

copyright: 'Copyright &copy; 2022 AJ Alt'

theme:
  name: 'material'
  logo: img/gradient_white_24dp.svg
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - tables

nav:
  - 'Getting Started': index.md
  - 'API Reference': api/index.html
  - 'Releases': changelog.md
